# Generated by Django 5.0.6 on 2024-06-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_car_id_alter_car_car_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
