# Generated by Django 5.0.6 on 2024-06-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
