# Generated by Django 5.0.6 on 2024-07-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipe',
        ),
    ]
